os:
  - linux
sudo: required
language: node_js
node_js:
  - "10.13.0"

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - develop

before_script:
  - npm install codecov -g
  - npm install -g codeclimate-test-reporter
  - npm install

script:
  - npm run test-coverage
  - npm run build

after_success:
  - codecov
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && CODECLIMATE_API_HOST=$CODECLIMATE_API_HOST CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN_MASTER codeclimate-test-reporter < coverage/lcov.info
  - test $TRAVIS_BRANCH = "develop" && test $TRAVIS_PULL_REQUEST = "false" && CODECLIMATE_API_HOST=$CODECLIMATE_API_HOST CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN_DEVELOP codeclimate-test-reporter < coverage/lcov.info

notifications:
  email:
    on_failure: change
    on_success: change
  slack: quantified-self-io:gWxqdRGo14eo9MoBMtIPX6ME

deploy:
  provider: npm
  email: jimmykane9@gmail.com
  skip_cleanup: true
  api_key:
    secure: updx7PMTwwztZFCuc+H4R5iLDS4E+83Fvcve97CaLr0CAZwIGWmEemGwU2bE/ZKEZZhXGkLtXeoCYvRWE8sUjJb/Ffppkx0ma8vDIrvKeTarnfHa7rQfQ9xx7hSgr1XRdytsusBFGuD6uM+4FIbgZ98zaSbgBeWfxhEokWj7+2eiAyjN6LbBm4IkuFhmOB4ez2u+zRTIe3+ZjezyjUFUcPV3xcZ8vbfaAJMOuGuvJEryInt+U4WxdSPgt41M1WWSWi1NsSY10zza1CBHqrCYpD59wAcbJLJ6jez4k89EKworzBcWfUf9XwJPAqbw8kfyXN7XSis9IkamB2g2fgfEJgEYdhm+u1gXMXZ3krQsygZUCTYu2kEcgZvlH7iEQZeqwxbttsLk+Ewzvg79jxRmleZbtei/iCcsL8TgHDCljfGXBj9SKpqAujzZubkk7c4A7CyC4rUGdC3eypPtd5CRXg+Zz5PWA1JpGdM+3Kb0YgsO9R10nUxhl9UdCziv6ZzjNS7d99VxZp/78nGyTNlGHrARs7Gm1WM8aCyRsnVrI+q51FQd6svX/FhSNXVHu+wjWXfz2RIoM+OGwHO97K9p03hSnkDk+5T2wNPFJIhl5BlRc5GNKXR0ghQ44KDK7d4+CO2hy6sRnLOgXSMrKCbfOl+huTicYPWnSV1LKiYV7Y8=
  on:
    branch: master
    repo: sports-alliance/sports-lib
